path_classifiers:
  test: "*/*/test_*.cpp"
  docs: "generate_javadoc.py"
queries:
- exclude: "$LGTM_SRC/build"
- exclude: "$LGTM_SRC/third_party"
extraction:
  cpp:
    before_index: "export CXXMICROSERVICE=$LGTM_SRC/CXXMicroService"
    index:
      build_command:
      - "git submodule init"
      - "git submodule update"
      - "mkdir build"
      - "cd build"
      - "cmake .."
      - "make -j2"
